#!/usr/bin/env bash

BLUE='\033[0;36m'
NC='\033[0m' # no color

echo -e "${BLUE}test A${NC}         test A.cpp against all available test cases"
echo -e "${BLUE}dbg A${NC}          to use testcase 1 file as input"
echo -e "${BLUE}s A${NC}            submits A.cpp to the corresponding judge"
echo -e "${BLUE}dbg A N${NC}        to use testcase N file as input"
echo -e "${BLUE}cpb t A.cpp -d${NC} to use keyboard as input"
echo -e "${BLUE}cpb clone${NC}      clone contest"
echo -e "${BLUE}ren${NC}            A_test.in1 -> A.in1    Basf.cpp -> B.cpp"
echo -e "${BLUE}build A${NC}        to compile and run your A.cpp file with some flags"
echo -e "${BLUE}comparator -h${NC}  for more informations"
echo -e "${BLUE}validate -h${NC}    for more informations"
